services:
  snapmaker-bot:
    build: .
    image: snapmaker-discord-bot:latest
    container_name: snapmaker-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./printers.json:/app/printers.json